### ISSUE TITLE
Add a column to the user database for a currency

### ISSUE THREAD

**Issue by Paughton** [TacticalTome/TacticalTome#2]
## Add a column to the user database for a Tactical Tome currency

We want to add the ability for the user to gain a currency for creating and writing popular strategy guides. However, we currently do not have a database column to support this. Using the `tacticaltome.sql` file, please add a column to the `user` table called `coins` with the type `big int`.

**Comment by Ulbrec87** [comment]
Hi, please see https://github.com/TacticalTome/TacticalTome/pull/9

**Comment by Paughton** [comment]
Complete https://github.com/TacticalTome/TacticalTome/pull/9
